"""Initialize database tables

Revision ID: 15bef6843f11
Revises:
Create Date: 2020-09-26 16:19:11.806301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bef6843f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefix',
            sa.Column('guild_id', sa.BigInteger(), nullable=False),
            sa.Column('prefix', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('tag',
            sa.Column('guild_id', sa.BigInteger(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('content', sa.String(), nullable=True),
            sa.Column('owner', sa.BigInteger(), nullable=True),
            sa.Column('last_modified', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('guild_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('prefix')
    # ### end Alembic commands ###
